[masters]
k3s-ctl-01 ansible_host=192.168.1.41 storage_ip=192.168.10.41 storage_mac=40:86:cb:35:a0:cd

[workers]
k3s-wrk-01 ansible_host=192.168.1.42 storage_ip=192.168.10.42 storage_mac=78:32:1b:a8:a4:c9
k3s-wrk-02 ansible_host=192.168.1.43 storage_ip=192.168.10.43 storage_mac=ec:22:80:a3:3a:91
k3s-wrk-03 ansible_host=192.168.1.44 storage_ip=192.168.10.44 storage_mac=74:da:da:33:ee:a7
# k3s-wrk-04 ansible_host=192.168.1.45 storage_ip=192.168.10.45 storage_mac=40:86:cb:35:a0:d0

#[edge_nodes]
#jetson-nano-01 ansible_host=192.168.1.25 storage_ip=192.168.10.45 storage_mac=42:da:55:f3:0b:b3

[k3s_cluster:children]
masters
workers

[all:vars]
# ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
